test1:
  batch_size: 64
  learning_rate: 0.001
  hidden_nodes: 20
  replay_memory_size: 100000
  discount_factor: 0.999
  network_sync_rate: 10
  max_steps: 1000
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.005